0x01

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-# if [ -z "$PYFILE" ]; then
-#     echo "Error: PYFILE environment variable not set."
-#     exit 1
-# fi
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable not set."
+    exit 1
+fi
 
 OUTPUT_FILE="${PYFILE}c"
 
